# .github/workflows/build-and-deploy-to-s3.yml
#
name: Build and Deploy to S3

# Controls when the action will run.
on:
  # Triggers the workflow on push for the master or main branch
  push:
    branches: [ master, main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: 'us-east-1'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Git LFS localhost s3 proxy
        run: bash scripts/clone-lfs.sh
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0" # Not needed with a .ruby-version file
          bundler-cache: true
      - name: "Build Site"
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production
      - name: "Remove .html extension"
        run: bash scripts/remove-html.sh
      - name: "Deploy to AWS S3"
        run: |
          aws s3 sync ./_site/ s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete --cache-control max-age=604800;
          aws s3 cp \
            --no-guess-mime-type \
            --content-type "text/html" \
            --metadata-directive REPLACE \
            s3://${{ secrets.AWS_S3_BUCKET_NAME }} \
            s3://${{ secrets.AWS_S3_BUCKET_NAME }} \
            --exclude 'assets/*' \
            --recursive
      - name: "Create AWS Cloudfront Invalidation"
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"